"""
SafeRoute AI — FastAPI Application Entry Point

Run locally:
    uvicorn api.main:app --reload --port 8000

API docs (auto-generated by FastAPI):
    http://localhost:8000/docs
    http://localhost:8000/redoc
"""

from __future__ import annotations

from pathlib import Path
import sys
from typing import Annotated, Optional

# Ensure project root is on sys.path regardless of execution directory
_API_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _API_DIR.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

_FRONTEND_DIST = _PROJECT_ROOT / "frontend" / "dist"
_FRONTEND_ASSETS = _FRONTEND_DIST / "assets"

from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

from api import schemas
from api.services import (
    evaluate_location_risk,
    get_cities,
    get_hotspot_by_rank,
    get_record_count,
    get_stats,
    is_data_loaded,
    query_hotspots,
)

# ──────────────────────────────────────────────────────────────────────────────
# App initialisation
# ──────────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="SafeRoute AI — Road Safety Hotspot Intelligence API",
    description=(
        "Exposes pre-computed road-safety hotspot intelligence from the "
        "SafeRoute AI analytical pipeline (ML + SHAP + RAG). "
        "\n\n"
        "**Responsible AI Notice:** Predictions indicate historically elevated risk "
        "based on accident patterns. They do NOT guarantee future accidents. "
        "SHAP attributions reflect model feature sensitivity, not proven causation. "
        "Safety guidance is sourced from authoritative MoRTH, IRC, and WHO documents."
    ),
    version="1.0.0",
    contact={"name": "SafeRoute AI — 1M1B Internship Project"},
    license_info={"name": "Research/Educational Use"},
)

# Mount frontend assets if compiled bundle exists
if _FRONTEND_ASSETS.is_dir():
    app.mount("/assets", StaticFiles(directory=str(_FRONTEND_ASSETS)), name="assets")

# ──────────────────────────────────────────────────────────────────────────────
# CORS — allow all origins for local frontend development.
# Restrict `allow_origins` in production.
# ──────────────────────────────────────────────────────────────────────────────

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],          # Restrict in production (e.g. ["http://localhost:3000"])
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ──────────────────────────────────────────────────────────────────────────────
# Exception handler for ValueError (converts to 400 Bad Request)
# ──────────────────────────────────────────────────────────────────────────────

@app.exception_handler(ValueError)
async def value_error_handler(request, exc: ValueError):
    return JSONResponse(status_code=400, content={"detail": str(exc)})


# ──────────────────────────────────────────────────────────────────────────────
# Endpoints
# ──────────────────────────────────────────────────────────────────────────────

@app.get(
    "/api",
    response_model=schemas.RootResponse,
    summary="API root — status and endpoint directory",
    tags=["Info"],
)
@app.get(
    "/api/info",
    response_model=schemas.RootResponse,
    include_in_schema=False,
)
def api_info():
    return schemas.RootResponse(
        name="SafeRoute AI",
        version="1.0.0",
        description=(
            "AI Road Safety Risk and Hotspot Analysis System. "
            "Exposes pre-computed ML + SHAP + RAG hotspot intelligence for "
            "Indian cities. Part of the 1M1B AI for Sustainability Internship."
        ),
        endpoints={
            "GET /": "SafeRoute AI Web Application",
            "GET /api": "API info and endpoint directory",
            "GET /health": "Health check",
            "GET /places/autocomplete": "Universal place search & geocoding autocomplete",
            "POST /journey/analyze": "Journey road-safety assessment along travel corridor",
            "POST /api/journey/ai-brief": "User-triggered generative AI safety briefing powered by IBM Bob",
            "POST /check-risk": "Evaluate road-safety risk for a single coordinate & time",
            "GET /hotspots": "List ranked hotspot intelligence records (filterable)",
            "GET /hotspots/{rank}": "Full intelligence for a specific hotspot by rank",
            "GET /cities": "Available cities in the dataset",
            "GET /stats": "Dataset statistics and tier distribution",
            "GET /docs": "Interactive API documentation (Swagger UI)",
        },
        responsible_ai_notice=(
            "SafeRoute AI uses historical accident data to identify high-risk "
            "location + time combinations. Predictions indicate elevated historical "
            "risk — NOT certainty of future accidents."
        ),
    )


@app.get(
    "/",
    summary="SafeRoute AI Web Application",
    tags=["Web UI"],
)
def root(request: Request):
    index_file = _FRONTEND_DIST / "index.html"
    if index_file.is_file():
        accept = request.headers.get("accept", "")
        # If caller explicitly asked for JSON (e.g. TestClient or API consumer without /api path)
        if "application/json" in accept and "text/html" not in accept:
            return api_info()
        return FileResponse(str(index_file), media_type="text/html")
    return api_info()


@app.get("/favicon.svg", include_in_schema=False)
def favicon():
    f = _FRONTEND_DIST / "favicon.svg"
    if f.is_file():
        return FileResponse(str(f), media_type="image/svg+xml")
    raise HTTPException(status_code=404, detail="Favicon not found")


@app.get("/ibm-bob-icon.png", include_in_schema=False)
def bob_icon():
    f = _FRONTEND_DIST / "ibm-bob-icon.png"
    if f.is_file():
        return FileResponse(str(f), media_type="image/png")
    raise HTTPException(status_code=404, detail="Icon not found")


@app.get(
    "/health",
    response_model=schemas.HealthResponse,
    summary="Health check — confirms data is loaded and service is ready",
    tags=["Info"],
)
def health():
    loaded = is_data_loaded()
    count = get_record_count()
    return schemas.HealthResponse(
        status="ok" if loaded else "degraded",
        data_file_loaded=loaded,
        record_count=count,
        api_version="1.0.0",
    )


@app.get(
    "/hotspots",
    response_model=schemas.HotspotsResponse,
    summary="List ranked hotspot intelligence records",
    description=(
        "Returns hotspot summary records ranked by predicted HIGH-risk probability. "
        "Filter by `city`, `risk_tier`, or `limit`.\n\n"
        "Examples:\n"
        "- `/hotspots?city=Pune&limit=5`\n"
        "- `/hotspots?risk_tier=HIGH&limit=20`\n"
        "- `/hotspots?city=Chandigarh&risk_tier=HIGH`"
    ),
    tags=["Hotspots"],
)
def list_hotspots(
    city: Annotated[
        Optional[str],
        Query(description="Filter by city name (case-insensitive). E.g. Pune, Delhi, Mumbai."),
    ] = None,
    risk_tier: Annotated[
        Optional[str],
        Query(description="Filter by risk tier: HIGH, MEDIUM, or LOW."),
    ] = None,
    limit: Annotated[
        int,
        Query(ge=1, le=500, description="Maximum number of records to return (1–500). Default: 20."),
    ] = 20,
):
    try:
        return query_hotspots(city=city, risk_tier=risk_tier, limit=limit)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.get(
    "/hotspots/{rank}",
    response_model=schemas.HotspotIntelligence,
    summary="Full hotspot intelligence for a specific rank",
    description=(
        "Returns the complete intelligence record for a given rank, including:\n"
        "- Location and spatial details\n"
        "- Time window and peak-window indicator\n"
        "- ML risk prediction and probability\n"
        "- SHAP contributing predictive factors\n"
        "- Authoritative safety guidance retrieved from MoRTH/IRC/WHO knowledge base\n\n"
        "Rank 1 = highest predicted HIGH-risk probability."
    ),
    tags=["Hotspots"],
)
def get_hotspot(rank: int):
    try:
        return get_hotspot_by_rank(rank)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))


@app.get(
    "/cities",
    response_model=schemas.CitiesResponse,
    summary="List cities available in the hotspot dataset",
    tags=["Info"],
)
def list_cities():
    cities = get_cities()
    return schemas.CitiesResponse(cities=cities, count=len(cities))


@app.get(
    "/stats",
    response_model=schemas.StatsResponse,
    summary="Dataset and prediction statistics",
    tags=["Info"],
)
def stats():
    try:
        return get_stats()
    except FileNotFoundError as e:
        raise HTTPException(status_code=503, detail=str(e))


@app.post(
    "/check-risk",
    response_model=schemas.CheckRiskResponse,
    summary="Evaluate road-safety risk for a specific geographic coordinate & travel time",
    description=(
        "Evaluates whether the requested location falls within evaluated training coverage "
        "and returns the corresponding spatiotemporal risk prediction. "
        "If outside model coverage, returns a transparent unsupported status without faking predictions."
    ),
    tags=["Risk Lookup"],
)
def check_risk_post(payload: schemas.CheckRiskRequest):
    return evaluate_location_risk(
        latitude=payload.latitude,
        longitude=payload.longitude,
        location_name=payload.location_name,
        travel_time=payload.travel_time,
        travel_date=payload.travel_date,
    )


@app.get(
    "/check-risk",
    response_model=schemas.CheckRiskResponse,
    summary="Evaluate road-safety risk (GET query params)",
    tags=["Risk Lookup"],
)
def check_risk_get(
    lat: Annotated[float, Query(description="Target latitude coordinate")],
    lon: Annotated[float, Query(description="Target longitude coordinate")],
    name: Annotated[Optional[str], Query(description="Location name/address")] = None,
    time: Annotated[Optional[str], Query(description="Planned travel time (e.g. 19:30)")] = None,
    date: Annotated[Optional[str], Query(description="Planned travel date")] = None,
):
    return evaluate_location_risk(
        latitude=lat,
        longitude=lon,
        location_name=name,
        travel_time=time,
        travel_date=date,
    )


@app.post(
    "/journey/analyze",
    response_model=schemas.JourneySafetyAssessment,
    summary="Evaluate road-safety hazards along a complete journey corridor",
    description=(
        "Spatially matches a journey (Origin → Destination) to OpenStreetMap road geometry, "
        "identifies ML-predicted urban hotspots and official Maharashtra highway blackspots along the corridor, "
        "and sequences them chronologically with expected arrival times, SHAP factors, and RAG prevention guidance.\n\n"
        "Strict Non-Routing Scope: Identifies pre-travel road hazards along the journey corridor — does NOT compute or steer routing."
    ),
    tags=["Journey Assessment"],
)
def analyze_journey(payload: schemas.JourneyRequest):
    try:
        from src.journey.journey_analyzer import analyze_journey_safety
        return analyze_journey_safety(payload)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Journey safety analysis error: {str(e)}")


@app.get(
    "/places/autocomplete",
    response_model=schemas.PlacesAutocompleteResponse,
    summary="Universal Place Search & Geocoding Autocomplete",
    description=(
        "Searches Maharashtra and Indian cities, towns, transit hubs, and localities. "
        "Backed by a fast local place index and a compliant rate-limited OpenStreetMap geocoder proxy with disk caching."
    ),
    tags=["Place Search"],
)
def places_autocomplete(
    q: Annotated[str, Query(description="Search term (e.g. 'Pune', 'Nag', 'Nashik')")] = "",
    limit: Annotated[int, Query(ge=1, le=20, description="Max results to return")] = 10,
):
    from src.journey.geocoding import search_places
    try:
        results = search_places(query=q, limit=limit)
        return schemas.PlacesAutocompleteResponse(
            query=q,
            count=len(results),
            results=results,
        )
    except Exception as e:
        # Graceful fallback: return empty list on any unexpected error, never expose raw internal stack
        return schemas.PlacesAutocompleteResponse(query=q, count=0, results=[])


@app.post(
    "/api/journey/ai-brief",
    response_model=schemas.JourneyAiBriefResponse,
    summary="Generate a concise AI Journey Safety Brief using IBM Bob",
    description=(
        "User-triggered generative AI safety briefing powered by IBM Bob. "
        "Synthesizes deterministic SafeRoute AI journey findings into a concise 4-6 bullet point brief. "
        "Strictly decision-support; does not invent hazards or guarantee zero-accident conditions."
    ),
    tags=["Journey Assessment"],
)
@app.post(
    "/journey/ai-brief",
    response_model=schemas.JourneyAiBriefResponse,
    include_in_schema=False,
)
def get_journey_ai_brief(payload: schemas.JourneyAiBriefRequest):
    from src.journey.bob_service import generate_bob_journey_brief
    hazard_dicts = [h.model_dump() for h in payload.hazards]
    result = generate_bob_journey_brief(
        route=payload.route,
        distance_km=payload.distance_km,
        duration=payload.duration,
        departure=payload.departure,
        risk_window=payload.risk_window,
        hazards=hazard_dicts,
    )
    return schemas.JourneyAiBriefResponse(**result)



